- name: Install yabai and skhd (m1 mac)
  community.general.homebrew:
    path: '/opt/homebrew/bin'
    name: ['yabai', 'skhd']
    state: present
  tags: yabai_skhd
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "arm64"

- name: Install zsh (intel mac)
  community.general.homebrew:
    path: '/usr/local/bin'
    name: ['yabai', 'skhd']
    state: present
  tags: yabai_skhd
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "x86_64"
