- name: Install zsh (m1 mac)
  community.general.homebrew:
    path: '/opt/homebrew/bin'
    name: zsh
    state: present
  tags: zsh
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "arm64"

- name: Install zsh (intel mac)
  community.general.homebrew:
    path: '/usr/local/bin'
    name: zsh
    state: present
  tags: zsh
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "x86_64"

- name: Install zsh (linux)
  apt: name=zsh
  tags: zsh
  when:
    - ansible_facts['os_family'] != "Darwin"

- name: Add zsh to /etc/shells
  shell: echo "/opt/homebrew/bin/zsh" >> /etc/shells
  tags: zsh
  become: true
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "arm64"

- name: Add zsh to /etc/shells
  shell: echo "/usr/local/bin/zsh" >> /etc/shells
  tags: zsh
  become: true
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "x86_64"

- name: Change shell to zsh (m1 mac)
  shell: chsh -s /opt/homebrew/bin/zsh
  tags: zsh
  become: true
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "arm64"

- name: Change shell to zsh (intel mac)
  shell: chsh -s /usr/local/bin/zsh
  tags: zsh
  become: true
  when:
    - ansible_facts['os_family'] == "Darwin"
    - ansible_architecture == "x86_64"
